### ISSUE TITLE
No way to install plugin?

### ISSUE THREAD

**Issue by ryumaou** [ken-bimmel/azgaar-to-obsidian#1]
I don't see either all the things I'd expect for an install or instructions.  I'd love to try this, but I don't see how.

**Comment by ken-bimmel** [comment]
Hey @ryumaou - I see I forgot to include a link to it! My apologies! You can find it here: https://ken-bimmel.github.io/azgaar-to-obsidian/

Otherwise, it's just a basic React app, so as long as you have Node installed you should be able to run it by cloning, installing, and running locally.
